model:
  type: Bert
dataset: sst2
data_config: glue
dataroot: /home/renshuhuai/TextAutoAugment/data
abspath: /home/renshuhuai/TextAutoAugment
aug: sst2
per_device_train_batch_size: 64
per_device_eval_batch_size: 128
epoch: 10
lr: 4e-5
max_seq_length: 128
n_aug: 8
num_op: 2
num_policy: 12
method: taa
topN: 1
ir: 1
seed: 59
trail: 1
train:
  npc: 50
valid:
  npc: 50
test:
  npc: 50  
num_search: 200

